server:
  port: 8080

spring:
  application:
    name: oauth2-authorization-server

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    org.springframework.security: INFO
    org.springframework.security.oauth2: DEBUG
